version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperSecure*Password1

  companyemployees.webapi:
    image: ${DOCKER_REGISTRY-}companyemployeeswebapi
    build:
      context: .
      dockerfile: src/CompanyEmployees.WebApi/Dockerfile
    depends_on:
      - sqlserver





